import{a as R,S as q,i as s}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))u(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const l of i.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function u(e){if(e.ep)return;e.ep=!0;const i=o(e);fetch(e.href,i)}})();function p(t,r){return R.get("https://pixabay.com/api/",{params:{key:"51711759-c98880f89c2a2cc3e02319f38",q:t.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}}).then(o=>o.data)}const g=document.querySelector(".gallery"),n=document.querySelector(".box-loader"),a=document.querySelector("#load-more"),E=new q(".gallery-item a",{captionsData:"alt",captionDelay:250});function m(t){const r=t.map(({webformatURL:o,largeImageURL:u,tags:e,likes:i,views:l,comments:v,downloads:S})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${u}">
    <img class="gallery-image" src="${o}" alt="${e}" loading="lazy"/>
  </a>

  <ul class="list-description">
    <li class="item-description"><strong>Likes</strong><p>${i}</p></li>
    <li class="item-description"><strong>Views</strong><p>${l}</p></li>
    <li class="item-description"><strong>Comments</strong><p>${v}</p></li>
    <li class="item-description"><strong>Downloads</strong><p>${S}</p></li>
  </ul>
</li>`).join("");g.insertAdjacentHTML("beforeend",r),E.refresh()}function P(){g.innerHTML=""}function y(){n==null||n.classList.remove("is-hidden")}function L(){n==null||n.classList.add("is-hidden")}function x(){a==null||a.classList.remove("is-hidden")}function f(){a==null||a.classList.add("is-hidden")}function H(){const t=g.firstElementChild;return t?t.getBoundingClientRect().height:0}const b=document.querySelector(".form"),O=document.querySelector("#load-more");let d="",c=1;const w=15;let h=0;b.addEventListener("submit",C);O.addEventListener("click",$);async function C(t){t.preventDefault();const r=t.target.elements["search-text"].value.trim();if(!r){s.error({title:"Please write a word!",position:"topRight"});return}d=r,c=1,h=0,P(),f();try{y();const o=await p(d,c);if(!o.hits||o.hits.length===0){s.error({title:`Sorry, there are no images matching your search "${d}". Please try again!`,position:"topRight"});return}h=o.totalHits??o.hits.length,m(o.hits),c*w<h?x():(f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){s.error({title:"Error",message:o.message,position:"topRight"})}finally{L(),b.reset()}}async function $(){try{c+=1,y();const t=await p(d,c);if(!t.hits||t.hits.length===0){f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}const r=H();m(t.hits),c*w>=h&&(f(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),r&&window.scrollBy({top:r*2,behavior:"smooth"})}catch(t){s.error({title:"Error",message:t.message,position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
